# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e9deeaba980a65cfe01426fd5007796279b06428eec30d9e691bf25cf537ae62b1a8eb5cc886176faf794447316a7b3b3810e275c1531beb5f9e7c7806adb5e6

test:
  secret_key_base: a48e8e5a21d1d68b48d9dc943cffa9ecf47fd1f2acc01384449c53efc260380c5d4bf4ff4a81f762fa9c657419be64ce261d6307c443917cbf5d327146631ffe

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
